import "./globals.css";

export const metadata = {
 title: 'Interior Designer Website',
 description: 'Generated by create vvebanextgen',
};

export default function RootLayout({ children }) {
  return (
   <html lang="en">
    <head>
     <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
     />
     <link rel="preconnect" href="https://fonts.googleapis.com" />
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
     <link
      href="https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;700&family=Raleway:wght@300;400;500;700&display=swap"
      rel="stylesheet"
     />
    </head>
    <body>{children}</body>
   </html>
  );
}
